{
 "title": "Qdrant",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cluster_enabled",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "cluster_enabled", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "cluster_pending_operations_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "cluster_pending_operations_total",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "cluster_voter",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster_voter", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "cluster_peers_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "cluster_peers_total", "legendFormat": "active cluster peers({{host}})" }
   ]
  },
  {
   "title": "cluster_term",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "cluster_term", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "cluster_commit",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster_commit", "legendFormat": "{{host}}" }
   ]
  },
  { "title": "Collections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "collections_total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "collections_total", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "collections_aggregated_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "collections_aggregated_total", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Collection vector",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "collections_vector_total", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "collections_full_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "collections_full_total", "legendFormat": "{{host}}" }
   ]
  },
  { "title": "gRPC API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "gRPC API responses duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "grpc_responses_avg_duration_seconds",
     "legendFormat": "avg"
    },
    {
     "expr": "grpc_responses_min_duration_seconds",
     "legendFormat": "min"
    },
    {
     "expr": "grpc_responses_max_duration_seconds",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "gRPC API responses total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "grpc_responses_total", "legendFormat": "success" },
    { "expr": "grpc_responses_fail_total", "legendFormat": "failed" }
   ]
  },
  {
   "title": "gRPC API RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "avg(irate(grpc_responses_total[$__interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "avg(irate(grpc_responses_fail_total[$__interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "REST API responses duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "avg(rest_responses_avg_duration_seconds)",
     "legendFormat": "avg"
    },
    {
     "expr": "avg(rest_responses_min_duration_seconds)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(rest_responses_max_duration_seconds)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "REST API responses total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    { "expr": "avg(rest_responses_total)", "legendFormat": "success" },
    { "expr": "avg(rest_responses_fail_total)", "legendFormat": "failed" }
   ]
  },
  {
   "title": "REST API RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "avg(irate(rest_responses_total[$__interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "avg(irate(rest_responses_fail_total[$__interval]))",
     "legendFormat": "failed"
    }
   ]
  }
 ]
}